const data = [
  {
    id: 1,
    name: "Handel Ercel",
    description: "Influencer",
    coverImg: "pic2.jpg",
    location: "US",
    platform: "Instagram",
    price: "100$",
  },
  {
    id: 2,
    name: "Handel Ercel",
    description: "Influencer",
    coverImg: "pic5.jpg",
    location: "US",
    platform: "Instagram",
    price: "100$",
  },
  {
    id: 3,
    name: "Handel Ercel",
    description: "Influencer",
    coverImg: "pic4.jpg",
    location: "Norway",
    platform: "Instagram",
    price: "100$",
  },
  {
    id: 4,
    name: "Handel Ercel",
    description: "Influencer",
    coverImg: "pic5.jpg",
    location: "US",
    platform: "Instagram",
    price: "100$",
  },
  {
    id: 5,
    name: "Handel Ercel",
    description: "Influencer",
    coverImg: "pic6.jpg",
    location: "US",
    platform: "Instagram",
    price: "100$",
  },
  {
    id: 6,
    name: "Handel Ercel",
    description: "Influencer",
    coverImg: "pic7.jpg",
    location: "US",
    platform: "Instagram",
    price: "100$",
  },
  {
    id: 7,
    name: "Handel Ercel",
    description: "Influencer",
    coverImg: "pic8.jpg",
    location: "US",
    platform: "Instagram",
    price: "100$",
  },
  {
    id: 8,
    name: "Handel Ercel",
    description: "Influencer",
    coverImg: "pic9.jpg",
    location: "US",
    platform: "Instagram",
    price: "100$",
  },
  {
    id: 9,
    name: "Handel Ercel",
    description: "Influencer",
    coverImg: "pic10.jpg",
    location: "US",
    platform: "Instagram",
    price: "100$",
  },
  {
    id: 10,
    name: "Handel Ercel",
    description: "Influencer",
    coverImg: "pic11.jpg",
    location: "US",
    platform: "Instagram",
    price: "100$",
  },
];

export default data;
